services:
  frontend:
    image: ${ECR_FRONTEND_IMAGE}
    container_name: community-frontend
    restart: unless-stopped
    environment:
      PORT: ${FRONTEND_PORT}
      KAKAO_MAP_JAVASCRIPT_KEY: ${KAKAO_MAP_JAVASCRIPT_KEY}
    volumes:
      - frontend_logs:/app/logs
    networks:
      - community-network

networks:
  community-network:
    name: community-network
    external: true

volumes:
  frontend_logs: